# Generated by Django 4.2.13 on 2024-05-14 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_img', models.ImageField(upload_to='service_img')),
                ('service_diss', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('profile_img', models.ImageField(upload_to='serviceman_pro')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.DateField(auto_created=True)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
