# Generated by Django 4.2.13 on 2024-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_services_serviceman_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceman',
            name='experience',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
