# Generated by Django 4.2.13 on 2024-05-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_serviceman_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_data',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.services'),
        ),
    ]
